// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (email, password_hash)
VALUES
    ($1, $2)
RETURNING
    id, email, created_at, updated_at, password_hash, is_chirpy_red
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.IsChirpyRed,
	)
	return i, err
}

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM
    users
`

func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUsers)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id, email, created_at, updated_at, password_hash, is_chirpy_red
FROM
    users
WHERE
    email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.IsChirpyRed,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id, email, created_at, updated_at, password_hash, is_chirpy_red
FROM
    users
WHERE
    id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.IsChirpyRed,
	)
	return i, err
}

const getUserByRefreshToken = `-- name: GetUserByRefreshToken :one
SELECT
    users.id, users.email, users.created_at, users.updated_at, users.password_hash, users.is_chirpy_red,
    refresh_tokens.token, refresh_tokens.user_id, refresh_tokens.expires_at, refresh_tokens.revoked_at, refresh_tokens.created_at, refresh_tokens.updated_at
FROM
    users
    INNER JOIN refresh_tokens ON users.id = refresh_tokens.user_id
WHERE
    refresh_tokens.token = $1
`

type GetUserByRefreshTokenRow struct {
	User         User         `json:"user"`
	RefreshToken RefreshToken `json:"refresh_token"`
}

func (q *Queries) GetUserByRefreshToken(ctx context.Context, token string) (GetUserByRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByRefreshToken, token)
	var i GetUserByRefreshTokenRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Email,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.PasswordHash,
		&i.User.IsChirpyRed,
		&i.RefreshToken.Token,
		&i.RefreshToken.UserID,
		&i.RefreshToken.ExpiresAt,
		&i.RefreshToken.RevokedAt,
		&i.RefreshToken.CreatedAt,
		&i.RefreshToken.UpdatedAt,
	)
	return i, err
}

const markUserAsChirpyRed = `-- name: MarkUserAsChirpyRed :exec
UPDATE
    users
SET
    is_chirpy_red = TRUE
WHERE
    id = $1
`

func (q *Queries) MarkUserAsChirpyRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markUserAsChirpyRed, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE
    users
SET
    email = $1,
    password_hash = $2
WHERE
    id = $3
RETURNING
    id, email, created_at, updated_at, password_hash, is_chirpy_red
`

type UpdateUserParams struct {
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Email, arg.PasswordHash, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.IsChirpyRed,
	)
	return i, err
}
